cargo-features = ["profile-rustflags"]

[package]
name = "EZDB"
version = "0.0.7"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Easy little database"
homepage = "https://github.com/lord-hellgrim/EZDB"
repository = "https://github.com/lord-hellgrim/EZDB"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


#[profile.test] 
#opt-level = 3

[profile.release]
rustflags = ["-C", "target-cpu=native", "-C", "target-feature=+avx2"]

[dependencies]
aes-gcm = "0.10.2"
blake3 = "1.5.0"
rand = "0.8.5"
rug = "1.22.0"
