[package]
name = "EZDB"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Easy little database"
homepage = "https://github.com/lord-hellgrim/EZDB"
repository = "https://github.com/lord-hellgrim/EZDB"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[profile.test] 
#opt-level = 3

[dependencies]
aes-gcm = "0.10.2"
